### ISSUE TITLE
Sistema de referências bibtex

### ISSUE THREAD

**Issue by robsonmars** [UniRobotica/Cursos#8]
@guilhermelopes19 Necessário incluir sistema de referências para facilitar a citação e geração de referências de forma automática, tal como ocorre com o Latex

**Comment by guilhermelopes19** [comment]
@robsonmars ok, irei fazer

**Comment by robsonmars** [comment]
disponibilizei a 1a versão da aula 02, fique a vontade para propor melhorias

**Comment by guilhermelopes19** [comment]
O que o senhor acha da biblioteca [pm4py](https://github.com/pm4py/pm4py-core)? O pm4py é uma biblioteca que permite realizar mineração de processos com python. Ela poderia ser útil no curso?

**Comment by guilhermelopes19** [comment]
Fiz o sistema de referências, as informações estão no pull request. Ficou como o senhor queria?
